name: テストの自動実行

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Phase7/library-system

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
        ports:
          - 3306:3306

    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v4

      - name: Node.js 20.x をセットアップ
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: 依存関係をインストール
        run: npm ci
        working-directory: ./Phase7/library-system

      - name: テストを実行
        run: npm run test
        working-directory: ./Phase7/library-system
        env:
          NODE_ENV: test
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: ソースコードを取得する
        uses: actions/checkout@v4

      - name: サーバーにデプロイする
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ec2-user/Forkup/Phase7/library-system
            git pull origin main
            npm ci
            npx sequelize-cli db:migrate
            pkill -f "ts-node.*app.ts" || true
            nohup npx ts-node --transpile-only app.ts &
