name: GitHub Actionsの基本的な動作確認

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: echo "Hello, GitHub Actions!" の実行
        run: echo "Hello, GitHub Actions!"
