name: テストの自動実行

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Phase7/library-system

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: library_system_test
        ports:
          - 3306:3306

    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v4

      - name: Node.js 20.x をセットアップ
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: './Phase7/library-system/package-lock.json'

      - name: 依存関係をインストール
        run: npm ci

      - name: テストを実行
        run: npm run test
        env:
          NODE_ENV: test
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: library_system_test

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: ソースコードを取得する
        uses: actions/checkout@v4

      - name: サーバーにデプロイする
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "Phase7/library-system/*"
          target: "/home/ec2-user/Forkup/"

      - name: アプリケーション再起動
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          timeout: 60s
          command_timeout: 5m
          script: |
            cd /home/ec2-user/Forkup/Phase7/library-system
            npm ci
            npx sequelize-cli db:migrate
            pkill -f "ts-node.*app.ts" || true

            setsid nohup npx ts-node --transpile-only app.ts > app.log 2>&1 < /dev/null &

            sleep 2

            if pgrep -f "ts-node.*app.ts" > /dev/null; then
              echo "起動成功"
            else
              echo "起動確認中（バックグラウンドで起動している可能性あり）"
            fi

            exit 0
